### ISSUE TITLE
GFX, order fields

### ISSUE THREAD

**Issue by Natim** [mozilla-services/amo-blocklist-ui#113]
Order of fields: 
- vendor,
- devices,
- OS,
- driver version,
- version comparator,
- feature,
- feature status,
- hardware,
- min version,
- max version.

**Comment by Natim** [comment]
@jvillalobos should we put details at the end?

**Comment by jvillalobos** [comment]
> @jvillalobos should we put details at the end?

If you mean name and bug number, yes.
