### ISSUE TITLE
Plugins, Drop filters for XPCOM ABI and Name.

### ISSUE THREAD

**Issue by Natim** [mozilla-services/amo-blocklist-ui#116]
Drop filters for XPCOM ABI and Name.

**Comment by Natim** [comment]
@jvillalobos do you mean the metadata name or the matchName field?

**Comment by Natim** [comment]
So we should remove `matchName`? How should we handle plugins that use it so far?

**Comment by Natim** [comment]
Oh maybe I misunderstood what you meant by filters, do you mean the column in the table or do you mean we should remove the field from the form?

**Comment by jvillalobos** [comment]
I meant the form fields. I doubt we'll ever need them, but there's little harm in keeping the columns, I suppose.

**Comment by Natim** [comment]
6371364
