### ISSUE TITLE
Blocklist UI behaving erratically

### ISSUE THREAD

**Issue by jvillalobos** [mozilla-services/amo-blocklist-ui#129]
I'm trying to make some changes to the blocklist, but the UI seems to be completely broken. Fields in existing blocklist items appear empty, and changing between views eventually stops working entirely. The Browser Console is showing multiple errors about variables being undefined or null.

**Comment by n1k0** [comment]
We very recently released a fix for what you describe in [kinto-admin v1.13.3](https://github.com/Kinto/kinto-admin/releases/tag/v1.13.3), which may not have been deployed to stage just yet. What's the version number printed in the footer in the version you use?

Also, could you please try using the [version hosted on Github Pages](https://kinto.github.io/kinto-admin/#/?_k=j35qj9) using the stage server URL (you'll need the Moz VPN and use your LDAP creds), and tell us if it works better for you?

**Comment by jvillalobos** [comment]
I'm using the production instance of the blocklist editor. And yes, the footer says it's version 1.13.2. The version on Github seems to be working correctly.

When will this change be applied to the blocklist editor? There are two major Thunderbird blocks that need work asap.

**Comment by Natim** [comment]
@jvillalobos Don't hesitate to use the Github admin to edit the items you are talking about.

We planned to deploy 1.13.3 in production yesterday but we have a regression to fix. It should be live early next week.

**Comment by jvillalobos** [comment]
That worked, thanks, but we need a better process to make updates to this system. Blocklisting emergencies require response times of under a day, so we need a solid system.

**Comment by Natim** [comment]
Production has been updated yesterday.
