### ISSUE TITLE
Plugin blocks should show `matchName` instead of `matchDescription`

### ISSUE THREAD

**Issue by jvillalobos** [mozilla-services/amo-blocklist-ui#130]
I'm trying to stage some Java plugin blocks for [bug 1358207](https://bugzilla.mozilla.org/show_bug.cgi?id=1358207). I was copying the new ones out of some old blocks, like [p1144](https://settings-writer.prod.mozaws.net/v1/admin/#/buckets/staging/collections/plugins/records/b3c55844-79d2-66dd-0d44-82fb4533307e/attributes?_k=lrxhii), but I noticed one important field missing: `matchName`. That field is needed in order to block Java plugin versions on certain platforms.

Maybe I got them mixed up when specifying this, but we should be showing the `matchName` field and not the unused `matchDescription` field in the plugin block form.

**Comment by jvillalobos** [comment]
This issue isn't urgent, by the way.

**Comment by Natim** [comment]
Why cannot we keep them both and use them when mandatory or ignore them otherwise?

**Comment by jvillalobos** [comment]
I just wanted to avoid having many useless fields like the old forms, but I don't mind if both are kept. Plugin blocks won't be needed soon enough.

**Comment by jvillalobos** [comment]
Can this be fixed in the next couple of weeks? The block has been sitting for a while waiting for this.

**Comment by jvillalobos** [comment]
This is already fixed, right?

**Comment by Natim** [comment]
Yes
