### ISSUE TITLE
Prompt user to choose between local and remote record on sync conflict

### ISSUE THREAD

**Issue by n1k0** [mozilla-services/amo-blocklist-ui#16]
Using the manual strategy, there can be conflict when collection is synchronized.

In a first version, there could be a dialog where the user is shown the local and remote version of the conflicting record, and they can choose what to do (*client wins*/*server wins*/*abort*)

**Comment by Natim** [comment]
This is taking care of here: https://github.com/Kinto/kinto-admin/issues/57
