### ISSUE TITLE
(minor) «Operation is unsecure» when cookies are blocked

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/amo-blocklist-ui#25]
`SecurityError: The operation is insecure.` and screen remains blank when cookies are refused.

IMO because of `localStorage`

**Comment by n1k0** [comment]
We should probably try/catch and render an error notification when this happens.

**Comment by n1k0** [comment]
Note that this is probably an edge case as most people aren't backlisting localStorage in their browser I suspect.
