### ISSUE TITLE
JSON schema is missing blockID for addons, plugins and gfx items.

### ISSUE THREAD

**Issue by Natim** [mozilla-services/amo-blocklist-ui#30]

**Comment by Natim** [comment]
Apparently Jorge said it is not used anymore but in case we want to be backward compatible with the existing ``blocklists.xml`` file it could be nice to have it.

**Comment by magopian** [comment]
We need it as it's used to build the "blocket item detail page url", eg https://addons.mozilla.org/en-us/firefox/blocked/i994 (`i994` is the `blockID`, which is `i` for item -- which means "addon" -- and `994` for the detail entry 994 in the database).

**Comment by magopian** [comment]
Closing as it's now fixed (`blockId` has been added to the schema)
