### ISSUE TITLE
An empty value should not end-up in the record.

### ISSUE THREAD

**Issue by Natim** [mozilla-services/amo-blocklist-ui#32]
Sometimes there are missing parameters in the XML file:

```
<versionRange severity="0" vulnerabilitystatus="1">
```

In that case we should not set an empty ``minVersion`` and ``maxVersion`` in the JSON record.

**Comment by magopian** [comment]
@Natim does that mean we don't want `minVersion` and `maxVersion` to not be required anymore, and remove their default values (currently `""`)?

**Comment by Natim** [comment]
I have no idea ;)

**Comment by magopian** [comment]
I see there's several entries with either no minVersion, maxVersion, or even severity, while they're all required at the moment in the schema (but with default values).
So I believe the current situation is "good enough", and will close this.

If someone knows more about that or has a strong opinion, please reopen.
