### ISSUE TITLE
Should target application be a list ?

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/amo-blocklist-ui#33]
I started to read and hack on the AMO blocklist code, and noticed the following:

https://dxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/nsBlocklistService.js#314-328
https://dxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/nsBlocklistService.js#1425-1439

It looks like `targetApplications` should be a list instead of an object like it is now.

**Comment by Natim** [comment]
Good point we are working on it.

**Comment by Natim** [comment]
There are also multiple attribute that doesn't seems to be in use: https://github.com/mozilla/addons-server/blob/master/src/olympia/blocklist/templates/blocklist/blocklist.xml#L6

**Comment by n1k0** [comment]
Can I let you guys creating the PR for the fixed schema?

**Comment by Natim** [comment]
Yes

**Comment by magopian** [comment]
Closing this now, it's been fixed already
