### ISSUE TITLE
Extra filters (in addition to id)

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/amo-blocklist-ui#35]
In addition to being able to filter on app id, there should be also : `["id", "name", "creator", "homepageURL", "updateURL"]`

Currently we only have `addonId` (which is `id` I suppose).

Source:
https://dxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/nsBlocklistService.js#999-1003

**Comment by Natim** [comment]
About ``name``, ``creator``, ``homepageURL`` and ``updateURL`` none of the current blocklist items uses them so we decided to get rid of them. Also ``id`` is mapped to ``guid``

**Comment by leplatrem** [comment]
> none of the current blocklist items uses them

Their addition in the Fx source code is not very old : https://github.com/mozilla/gecko-dev/commit/3bf22859b

**Comment by Natim** [comment]
While reading the Firefox source code with @leplatrem we realized that these attribute may be used to block addons that have the same homepageURL or updateURL or creator or name. Today we didn't use this feature yet but should we consider that this feature is not useful nevertheless?

@jvillalobos do you have any thoughts about that?

**Comment by jvillalobos** [comment]
We added them at a time where we didn't expect to have add-on id integrity (via signing, which we have now). They could still be useful to block multiple add-ons that follow certain patterns, but I don't know if we'll end up actually using them.

I think it's fine to not include them for now.

**Comment by Natim** [comment]
Thank you @jvillalobos for your clarification :+1:

**Comment by magopian** [comment]
Closing for now, reopen if you feel this is needed
