### ISSUE TITLE
Should we use record id as `blockId`? 

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/amo-blocklist-ui#36]
There is a notion of `blockId`, I plan to use the record id. Should we use another explicit mandatory field ? 
https://dxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/nsBlocklistService.js#1029

**Comment by leplatrem** [comment]
Oh I hadn't see #30

**Comment by magopian** [comment]
Answered in #30
