### ISSUE TITLE
Add field with date of creation

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/amo-blocklist-ui#39]
Used here: https://github.com/mozilla/addons-server/blob/master/src/olympia/blocklist/templates/blocklist/blocked_detail.html#L44-L46

**Comment by Natim** [comment]
We do not have this information in the XML nor on the AMO blocklist detail page.

We should investigate if we do have this information in the DB.

**Comment by jvillalobos** [comment]
It must be stored in the DB, since the blocklist pages do show the creation date.

**Comment by Natim** [comment]
> since the blocklist pages do show the creation date.

Oh I missedthat.

**Comment by leplatrem** [comment]
Done in #73
