### ISSUE TITLE
Make the target applications choice a dropdown

### ISSUE THREAD

**Issue by magopian** [mozilla-services/amo-blocklist-ui#44]
This is a request from @jvillalobos

I believe the available target applications are (from https://github.com/mozilla/addons-server/blob/master/src/olympia/constants/applications.py):
- Firefox: {ec8030f7-c20a-464f-9b0e-13a3a9e97384}
- Thunderbird: {3550f703-e582-4d05-9a08-453d09bdfdc6}
- Seamonkey: {92650c4d-4b8e-4d2a-b7eb-24ecf4f6b63a}
- Sunbird: {718e30fb-e89b-41dd-9da7-e25a45638b28}
- Mobile: {a23983c0-fd0e-11dc-95ff-0800200c9a66}
- Android: {aa3c5121-dab2-40e2-81ca-7ea25febc110}
- Mozilla: {86c18b42-e466-45a9-ae7a-9b95ba6f5640}

Not sure all of those are actually used in the xml file.

**Comment by jvillalobos** [comment]
We only need these:

* Firefox: {ec8030f7-c20a-464f-9b0e-13a3a9e97384}
* Thunderbird: {3550f703-e582-4d05-9a08-453d09bdfdc6}
* Seamonkey: {92650c4d-4b8e-4d2a-b7eb-24ecf4f6b63a}
* Android: {aa3c5121-dab2-40e2-81ca-7ea25febc110}

**Comment by magopian** [comment]
It's easy to change the `Application id` text field into a list, but it'll be a list of application GUIDs.

To have meaningful names instead (firefox, thunderbird...), it'll need [enumNames](https://github.com/mozilla-services/react-jsonschema-form/issues/25). Filed #54 for this
