### ISSUE TITLE
The vulnerability status field should have labels instead of simple numbers

### ISSUE THREAD

**Issue by magopian** [mozilla-services/amo-blocklist-ui#45]
This is a request from @jvillalobos

Note: this field only applies to plugins, not to add-ons

**Comment by magopian** [comment]
@jvillalobos could you please share the labels for each of the statuses?

**Comment by jvillalobos** [comment]
1 - Update available
2 - Update unavailable

**Comment by magopian** [comment]
This will need [enumNames](https://github.com/mozilla-services/react-jsonschema-form/issues/25) in `react-jsonschema-form`
