### ISSUE TITLE
Allow entering multiple devices for a gfx block entry

### ISSUE THREAD

**Issue by magopian** [mozilla-services/amo-blocklist-ui#47]
Citation: "In the gfx form on AMO, we just add the list of devices separated by
spaces, since they are often 5 or more. It'd be nice to support that."

This is a request from @jvillalobos

**Comment by magopian** [comment]
@jvillalobos how many devices at once are we talking about here? Could you live with the current version for the moment, and then we'll see if we can prioritize this later?

**Comment by jvillalobos** [comment]
This is a dupe of issue #37

**Comment by magopian** [comment]
thanks, closing
