### ISSUE TITLE
Add support for more content-related properties to records

### ISSUE THREAD

**Issue by n1k0** [mozilla-services/amo-blocklist-ui#5]
Quoting Jorge:

> String name
> String why
> String who 
> String bug
> These properties are used to display the block on AMO: https://addons.mozilla.org/firefox/blocked/i990. In the future, I'd like to at least merge "why" and "who", but ideally I'd prefer to have a set of predefined and localized explanations, with the option to have custom text, since most blocks have the same copy.

**Comment by n1k0** [comment]
@minusfive Could we imagine linking string ids or whatever identifiers available from your django environment instead of implementing a full internalization UI for these fields?

**Comment by minusfive** [comment]
@n1k0 I think you might have the wrong Jorge?

**Comment by n1k0** [comment]
Oh. My. God. I'm sorry @minusfive, I was actually pinging @jvillalobos.

**Comment by minusfive** [comment]
@n1k0 hehe, no worries. Not many Jorge Villalobos around.

**Comment by jvillalobos** [comment]
@n1k0 Sorry for the delay replying here. I'm not sure what you mean about linking identifiers, but we'd like to remove any dependencies to the django environment on AMO.
