### ISSUE TITLE
TargetApplication should be a list for add-ons

### ISSUE THREAD

**Issue by magopian** [mozilla-services/amo-blocklist-ui#52]
See https://github.com/mozilla/addons-server/blob/f391803a83231a8fbbcbb172dc26f2ef4b9b5c39/src/olympia/blocklist/templates/blocklist/blocklist.xml#L11-L17

If we do that for add-ons, it would also make sense to do that for plugins to stay coherent (also, it would make it possible to have 0 target application, or a target application with required fields, see #31)

**Comment by leplatrem** [comment]
Fixed in #53
