### ISSUE TITLE
Provide meaningful labels for the "target application id" field

### ISSUE THREAD

**Issue by magopian** [mozilla-services/amo-blocklist-ui#54]
This is following #44
- Firefox: {ec8030f7-c20a-464f-9b0e-13a3a9e97384}
- Thunderbird: {3550f703-e582-4d05-9a08-453d09bdfdc6}
- Seamonkey: {92650c4d-4b8e-4d2a-b7eb-24ecf4f6b63a}
- Android: {aa3c5121-dab2-40e2-81ca-7ea25febc110}

**Comment by magopian** [comment]
Related: #45

**Comment by magopian** [comment]
This needs an implementation of `enumNames` in `react-jsonschema-form`

**Comment by Natim** [comment]
This has been released in the last version of react-json-schema-form. It will be available in the next release of kinto-admin.

**Comment by Natim** [comment]
However we should add the names here.
