### ISSUE TITLE
Add osversion to Gfx schema

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/amo-blocklist-ui#61]
See: 
https://dxr.mozilla.org/mozilla-central/source/widget/GfxInfoBase.cpp#510

**Comment by Natim** [comment]
It doesn't appear to be used here: https://github.com/mozilla/addons-server/blob/a642d7c3d1966932292e177cd5871937085f0009/src/olympia/blocklist/templates/blocklist/blocklist.xml#L74-L106

Closing as wontfix.
