### ISSUE TITLE
Add model,product,manufacturor,hardware to Gfx

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/amo-blocklist-ui#62]
See https://dxr.mozilla.org/mozilla-central/source/widget/GfxInfoBase.cpp#593-616

**Comment by Natim** [comment]
model, product are not in the blocklist.xml template.

manufacturor is not present however we have a vendor tag [here](https://github.com/mozilla/addons-server/blob/a642d7c3d1966932292e177cd5871937085f0009/src/olympia/blocklist/templates/blocklist/blocklist.xml#L103-L105)
Hardware is [here](https://github.com/mozilla/addons-server/blob/a642d7c3d1966932292e177cd5871937085f0009/src/olympia/blocklist/templates/blocklist/blocklist.xml#L103-L105)

**Comment by Natim** [comment]
@jvillalobos can you confirm that we should have hardware or can we get rid of it since it wasn't used so far?

**Comment by jvillalobos** [comment]
I don't know much about Gfx blocks. I only deploy them per the graphics team's instructions. I'd prefer that we keep it to stay on the safe side.

**Comment by leplatrem** [comment]
Apparently there are references to them in the android codebase:
https://dxr.mozilla.org/mozilla-central/source/widget/android/GfxInfo.cpp#433-494

**Comment by magopian** [comment]
@leplatrem this is on the client, not on the xml generating code. Our rationale was that if there's no way to generate such attributes, and if there's no such attribute in the xml, then there's no way it was used. Not saying it will never be, but if we're just trying to be "feature complete" with the current solution, it's not needed.

I won't agree against having it however ;)

**Comment by Natim** [comment]
I am bit worried about this because there are no trace of this information in the olympia code base (except for hardware and vendor).

Does this means that the android blocklists is handled elsewhere?

**Comment by jvillalobos** [comment]
No, all blocklists are handled in the same place. It's more likely that those blocklist features were added to the client without letting us know. It has happened before. Some people assume we just manually edit the XML file and have complete flexibility.

**Comment by Natim** [comment]
So we should probably be good there. Adding hardware though.
