### ISSUE TITLE
Add versionRange[minVersion,maxVersion] to Gfx

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/amo-blocklist-ui#63]
See https://dxr.mozilla.org/mozilla-central/source/widget/GfxInfoBase.cpp#472-501

**Comment by Natim** [comment]
We do not have any versionRange tag for GFX: https://github.com/mozilla/addons-server/blob/a642d7c3d1966932292e177cd5871937085f0009/src/olympia/blocklist/templates/blocklist/blocklist.xml#L71-L109

Closing as wontfix.
