### ISSUE TITLE
Switch Gfx feature to enum

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/amo-blocklist-ui#64]
* "DIRECT2D"
* "DIRECT3D_9_LAYERS"
* "DIRECT3D_10_LAYERS"
* "DIRECT3D_10_1_LAYERS"
* "DIRECT3D_11_LAYERS"
* "DIRECT3D_11_ANGLE"
* "HARDWARE_VIDEO_DECODING"
* "OPENGL_LAYERS"
* "WEBGL_OPENGL"
* "WEBGL_ANGLE"
* "WEBGL_MSAA"
* "STAGEFRIGHT"
* "WEBRTC_HW_ACCELERATION_ENCODE"
* "WEBRTC_HW_ACCELERATION_DECODE"
* "WEBRTC_HW_ACCELERATION"
* "CANVAS2D_ACCELERATION"

See https://dxr.mozilla.org/mozilla-central/source/widget/GfxInfoBase.cpp#326-358

**Comment by Natim** [comment]
This is another case for ``enumNames`` and ``enums``.

**Comment by magopian** [comment]
Actually, no need for `enumName`, as it's a simple enum ;)
