### ISSUE TITLE
Add missing comparators to Gfx

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/amo-blocklist-ui#65]
See
* "NOT_EQUAL"
* "BETWEEN_EXCLUSIVE"
* "BETWEEN_INCLUSIVE"
* "BETWEEN_INCLUSIVE_START"

https://dxr.mozilla.org/mozilla-central/source/widget/GfxInfoBase.cpp#391-409

**Comment by Natim** [comment]
There are not in the current blocklist.xml file but it doesn't harm to add them in the JSON Schema in case they happen in the feature.

**Comment by magopian** [comment]
Fixed by #66
