### ISSUE TITLE
Add missing feature status to Gfx

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/amo-blocklist-ui#66]
https://dxr.mozilla.org/mozilla-central/source/widget/GfxInfoBase.cpp#369-386

**Comment by Natim** [comment]
- STATUS_OK
- DISCOURAGED
- BLOCKED_OS_VERSION

https://github.com/mozilla-services/amo-blocklist-ui/blob/master/amo-blocklist.json#L278-L287
