### ISSUE TITLE
Details for GFX and Certificates

### ISSUE THREAD

**Issue by Natim** [mozilla-services/amo-blocklist-ui#76]
While looking in Olympia database it appears that there are some information details for GFX drivers and certificates that are not public.

This means we should either ask for an export or read the database in order to migrate this informations.

@jvillalobos what do you think? Should we import this informations? (GFX bug numbers/Certificates names)?

**Comment by jvillalobos** [comment]
Yes, gfx and cert blocks aren't displayed anywhere. Keeping a reference to the bug is important to us, so it should be stored. The name is not particularly important.

**Comment by leplatrem** [comment]
I marked this as resolved, since a JSON view was added on addons-server to obtain those, and details fields were added in the schema.
