### ISSUE TITLE
os and xpcomabi should be comma-separated

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/amo-blocklist-ui#85]
See https://dxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/nsBlocklistService.js#231-241

And here https://blocklist.addons.mozilla.org/blocklist/3/%7Bec8030f7-c20a-464f-9b0e-13a3a9e97384%7D/44.0a1/ I could find **one** example for addons:
```xml
<emItem blockID="i75" os="Darwin,Linux" id="firebug@software.joehewitt.com"><versionRange minVersion="1.9.0" maxVersion="1.9.0" severity="1"><targetApplication id="{ec8030f7-c20a-464f-9b0e-13a3a9e97384}"><versionRange minVersion="9.0a1" maxVersion="9.*"/></targetApplication></versionRange><prefs></prefs></emItem>
```

Currently, the `os` field on addons is a string, so that would work. Maybe we could add some regexp as a safety net.

**Comment by n1k0** [comment]
Two words. Gosh. Grmbl.

**Comment by leplatrem** [comment]
> how it should look like

It should be something like `\w(,\w)*` (untested)

No rush. Nothing is validated in the field on current system in Django

**Comment by n1k0** [comment]
Just tested that in the console, seems to work well.
