### ISSUE TITLE
vulnerabilityStatus should be present only when severity is equal to 0

### ISSUE THREAD

**Issue by Natim** [mozilla-services/amo-blocklist-ui#89]
In the current server code, there is this validation rule.

https://github.com/mozilla/addons-server/blob/master/src/olympia/blocklist/forms.py#L14-L16

Should we have it in the admin too?

**Comment by jvillalobos** [comment]
Yeah, that restriction is real. Though, for the past couple of years, we've only used severity = 0 and I don't expect that to change.

**Comment by Natim** [comment]
Ok good to know thanks :)
