### ISSUE TITLE
Custom validation rules for severity and vulnerability

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/amo-blocklist-ui#96]
https://github.com/mozilla/addons-server/blob/master/src/olympia/blocklist/forms.py#L11-L16

Requires https://github.com/mozilla-services/react-jsonschema-form/pull/163

**Comment by Natim** [comment]
Apparently mozilla-services/react-jsonschema-form#163 was merged, what is the next step on this one?

**Comment by n1k0** [comment]
Unfortunately these validation rules must be written in JavaScript and not in JSON, and we don't plan on adding support for user contributed js code in the kinto-admin, so...

**Comment by Natim** [comment]
Ok closing then.
