### ISSUE TITLE
additionalProperty schema

### ISSUE THREAD

**Issue by Natim** [mozilla-services/amo-blocklist-ui#98]
We also need to allow the schema additional property:

```instance additionalProperty "schema" exists in instance when not allowed```

That is added by kinto to tell which version of the schema has been used for this record.

**Comment by leplatrem** [comment]
Note that this field should be hidden disabled and optional.

Indeed we're not sure to enable jsonschema validation in the server yet (currently not enabled)

**Comment by n1k0** [comment]
Fixed by https://github.com/Kinto/kinto-admin/pull/49
